# Main configuration for RAG system
paths:
  docs_dir: "data/documents"
  vector_store: "data/vector_store"
  cache_dir: "data/cache"
  logs_dir: "logs/rag_system.log"
  models: "models"

model:
  embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
  cross_encoder: "cross-encoder/ms-marco-MiniLM-L6-v2"
  llm_model: ""

retrieval:
  chunk_size: 100
  chunk_overlap: 10
  similarity_threshold: 0.6
  top_k: 3
  reranking_enabled: true
  hybrid_search_enabled: true

cache:
  enable: true
  redis_url: "redis://localhost:6379"
  ttl: 3600
  max_size: 1000

api:
  host: "0.0.0.0"
  port: 8000
  debug: true

auth:
  tokens:
    - "aidc_dev"  # 修改为列表格式

info:
  True


